export const FURNACE_TEMPERATURE_MIN_C = 25;
export const FURNACE_TEMPERATURE_MAX_C = 1100;

export const FURNACE_TEMPERATURE_RANGE_LABEL = `${FURNACE_TEMPERATURE_MIN_C}-${FURNACE_TEMPERATURE_MAX_C}°C`;
