export const FURNACE_TEMPERATURE_MIN_C = 25;
export const FURNACE_TEMPERATURE_MAX_C = 1100;
export const FURNACE_HARDWARE_SEGMENT_COUNT = 30;
export const FURNACE_PROGRAM_SEGMENT_COUNT = 27;
export const FURNACE_TRANSIENT_SEGMENT_START = FURNACE_PROGRAM_SEGMENT_COUNT + 1;

export const FURNACE_TEMPERATURE_RANGE_LABEL = `${FURNACE_TEMPERATURE_MIN_C}-${FURNACE_TEMPERATURE_MAX_C}°C`;

export const isFurnaceTransientSegment = (segment: number): boolean => (
  segment >= FURNACE_TRANSIENT_SEGMENT_START && segment <= FURNACE_HARDWARE_SEGMENT_COUNT
);
