packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': set this to true or false
  better-sqlite3: set this to true or false
  core-js: set this to true or false
  electron: set this to true or false
  esbuild: set this to true or false
  sqlite3: set this to true or false

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@serialport/bindings-cpp'
  - electron
  - electron-winstaller
  - esbuild

onlyBuiltDependencies:
  - better-sqlite3
